export type Locale = 'zh' | 'en';
export type Item = { title: string; description: string };
export type Scene = Item & { category: number; input: string; output: string };
const categories = [['全部场景','写作','编程','客服','教育','营销','数据','产品','个人'],['All scenarios','Writing','Code','Support','Education','Marketing','Data','Product','Personal']];
const sceneRows = [
[1,'从空白到初稿','文章大纲、博客与长文，让表达更有条理。','主题、读者、语气和篇幅','大纲与可编辑的文章初稿','From blank page to first draft','Outline articles, blogs and long-form stories.','Topic, audience, tone and length','An outline and editable first draft'],
[1,'让每封邮件恰到好处','将零散想法写成清晰、礼貌的商务邮件。','收件人、背景与期望行动','邮件草稿与主题行','Emails that land','Turn scattered thoughts into clear, considerate emails.','Recipient, context and desired action','An email draft and subject line'],
[1,'会议结束，行动开始','整理讨论、决策与负责人的行动清单。','会议文字记录','摘要、决策与待办事项','Meetings into momentum','Extract decisions and owner-based action items.','Meeting transcript','Summary, decisions and next steps'],
[2,'读懂陌生代码','拆解函数、依赖关系与潜在边界条件。','代码片段和问题','逐步解释与改进建议','Understand unfamiliar code','Unpack functions, dependencies and edge cases.','Code snippet and question','Step-by-step explanation and suggestions'],
[2,'更快定位问题','根据错误日志提出可验证的排查路径。','日志、运行环境与复现步骤','诊断假设和检查清单','Debug with direction','Find testable paths forward from error logs.','Logs, environment and reproduction','Hypotheses and a debugging checklist'],
[2,'测试覆盖更周全','补充正常、异常与边界测试的思路。','函数与预期行为','测试用例草稿','Think through test coverage','Explore happy paths, failure modes and boundaries.','Function and expected behavior','Draft test cases'],
[3,'客服回复更一致','根据已提供的规则草拟准确友好的答复。','客户问题与服务政策','带依据的回复草稿','Consistent support replies','Draft thoughtful answers grounded in your policies.','Customer question and service policy','A response draft with references'],
[3,'工单自动归类','整理问题类型、紧急程度与处理建议。','去标识化工单内容','分类和建议处理顺序','Triage incoming tickets','Organize issues by category, urgency and next step.','De-identified ticket text','Categories and suggested priorities'],
[3,'跨语言服务','为不同语言的客户调整表达和语气。','原始回复与目标语言','本地化回复草稿','Support across languages','Adapt your response to a different language and tone.','Original response and target language','A localized reply draft'],
[4,'复杂概念，简单解释','用类比、例子与逐步推导理解知识。','知识点与学习水平','分层解释和理解检查','Make complexity click','Learn with analogies, examples and guided reasoning.','Concept and learner level','Layered explanation and comprehension checks'],
[4,'为你安排学习路径','将学习目标拆成每天可以执行的小任务。','目标、时间与基础','阶段计划与练习建议','Build a learning path','Turn a goal into manageable daily learning tasks.','Goal, available time and starting level','Milestones and suggested practice'],
[4,'练习后的即时反馈','指出推理或表达中的不足并给出提示。','习作、答案与评价标准','反馈与改进方向','Feedback that helps','Find gaps in reasoning or expression with guided hints.','Work, answer and assessment criteria','Feedback and improvement directions'],
[5,'一个想法，多种表达','生成不同渠道与受众的文案变体。','产品卖点与渠道','广告和社交内容草稿','One idea, many expressions','Explore copy for different channels and audiences.','Product benefits and channel','Ad and social copy drafts'],
[5,'内容日历不再空白','围绕主题建立可持续的内容发布计划。','品牌、目标与周期','内容日历和选题','Fill your content calendar','Build a coherent publishing plan around a theme.','Brand, goals and time period','Content calendar and topic ideas'],
[5,'把访谈变成洞察','归纳客户声音，提取反复出现的需求。','去标识化访谈记录','主题、痛点和引用','Listen for insights','Find recurring needs in customer conversations.','De-identified interview notes','Themes, pain points and excerpts'],
[6,'表格里的故事','从小型数据表提取趋势与值得追问的变化。','表格与指标定义','趋势摘要和后续问题','Find the story in a table','Surface trends and changes worth investigating.','Table and metric definitions','Trend summary and follow-up questions'],
[6,'让指标说人话','解释指标定义、波动原因与分析路径。','指标和业务背景','解释与待验证假设','Metrics in plain language','Explain definitions, movements and analysis paths.','Metrics and business context','Explanation and hypotheses to verify'],
[6,'报告从草稿开始','将分析结果组织成便于决策的汇报。','已核实的数据与结论','报告草稿和图表建议','Start your next report','Structure verified findings into a decision-ready draft.','Verified data and conclusions','Report draft and chart suggestions'],
[7,'从反馈到需求','把零散反馈整理为问题、目标与验收条件。','用户反馈与约束','需求说明草稿','Feedback into requirements','Turn scattered feedback into goals and acceptance criteria.','Feedback and constraints','Requirements draft'],
[7,'把经验变成流程','整理重复工作，形成容易遵循的操作指南。','现有操作步骤','SOP与检查清单','Experience into process','Document repeatable work as an easy-to-follow guide.','Current operating steps','SOP and checklist'],
[7,'上线前查漏补缺','梳理发布风险、依赖和准备事项。','发布内容和团队分工','发布检查清单','Prepare for launch','Identify dependencies, risks and readiness tasks.','Release scope and team responsibilities','Launch checklist'],
[8,'让计划可以执行','将复杂目标拆成优先级明确的小步骤。','目标、截止时间与约束','行动计划','Make a plan actionable','Break a complex goal into prioritized steps.','Goal, deadline and constraints','Action plan'],
[8,'阅读之后留下知识','将长文整理成要点、问题与笔记。','文章文字与关注主题','摘要和阅读笔记','Keep what you read','Turn long text into key points, questions and notes.','Article text and focus topic','Summary and reading notes'],
[8,'简历表达更清晰','让经历描述具体、有重点，保留真实事实。','真实经历与目标岗位','简历措辞建议','Tell your career story','Clarify experience while keeping every claim factual.','Real experience and target role','Resume wording suggestions']
] as const;
export function getContent(locale: Locale) {
 const zh = locale === 'zh';
 return {
 zh, categories: categories[zh?0:1],
 nav: zh?['核心能力','使用场景','工作流程','价格方案']:['Capabilities','Use cases','How it works','Pricing'],
 hero: zh?['你的想法，','下一步已就绪。','从第一行灵感，到最后一份交付。Luma AI 帮你写作、编程、分析与探索，让每一个好想法都能向前一步。']:['Your next idea.','Already in motion.','From the first spark to the final deliverable. Write, code, analyze and explore with an AI workspace that moves ideas forward.'],
 cta: zh?'体验产品演示':'Try the demo', explore: zh?'探索使用场景':'Explore use cases',
 capabilities: (zh?[
 ['写出更好的内容','从大纲到改稿，为邮件、文章和方案找到清晰的表达。'],['让代码更易理解','解释逻辑、探索修复方案，补全测试与文档。'],['连接你的知识','围绕你提供的资料回答问题，并提示核实来源。'],['看见数据中的线索','整理表格、解释指标，为下一步分析提出方向。'],['跨越语言边界','翻译与调整语气，让表达更贴近目标读者。'],['与团队一起推进','分享结构化草稿，让团队在统一上下文中讨论。']
 ]:[['Write with clarity','Find the right words for emails, articles and proposals, from outline to revision.'],['Make code understandable','Explain logic, explore fixes, and draft tests and documentation.'],['Connect your knowledge','Ask questions about supplied material and verify references.'],['See signals in data','Summarize tables, explain metrics and discover questions worth asking.'],['Go beyond language','Translate and adapt tone for the people you want to reach.'],['Move work forward together','Share structured drafts with a common context for team review.']]).map(([title,description])=>({title,description})),
 scenes: sceneRows.map(r=>({category:r[0],title:r[zh?1:5],description:r[zh?2:6],input:r[zh?3:7],output:r[zh?4:8]})) as Scene[],
 features: (zh?[
 ['上下文，让答案更贴近你','把目标、参考资料与限制条件放在同一个工作区。清晰的背景帮助 AI 给出更合适的草稿，也让你更容易检查结果。','目标与语气可调整','参考内容集中管理','多轮修改保持方向'],
 ['从回答，到可以交付的成果','按清单、表格、邮件或代码组织输出。继续修改语气、长度和结构，再复制到你的工作工具中。','结构化输出','快速切换表达方式','复制并继续编辑'],
 ['让人的判断始终在场','把 AI 当作协作者：检查关键事实、核实代码与数据，对最终发布的内容负责。演示中不会上传或保存你的输入。','明确能力边界','敏感信息先去标识化','关键成果人工审核']
 ]:[['Context makes it yours','Bring goals, references and constraints into one workspace. Clear context makes drafts more relevant and easier to review.','Adjust goals and tone','Keep reference material together','Refine through multiple rounds'],['Beyond an answer. Toward a deliverable.','Shape output as a checklist, table, email or code. Refine tone, length and structure, then take it into your tools.','Structured output','Explore different expressions','Copy and keep editing'],['Your judgment stays in the loop','Treat AI as a collaborator: verify facts, test code and check data before publishing. This demo never uploads or saves your input.','Clear capability boundaries','De-identify sensitive material','Review important deliverables']]),
 steps: (zh?[['描述目标','说明你想完成什么，以及谁会使用结果。'],['补充上下文','提供资料、格式、语气和限制条件。'],['生成与迭代','查看草稿，继续追问并调整表达。'],['检查并交付','核实事实、测试代码，将成果复制到工作工具。']]:[['Set a goal','Describe the task and who the result is for.'],['Add context','Supply references, format, tone and constraints.'],['Generate and refine','Review a draft, ask follow-ups and adjust.'],['Check and deliver','Verify facts, test code and take the result into your tools.']]).map(([title,description])=>({title,description})),
 faq: (zh?[
 ['Luma AI 是真实上线的 AI 服务吗？','这是一个概念产品落地页。产品界面、套餐与用户反馈用于展示设计和交互，暂未接入真实模型或支付服务。'],['演示会把我输入的内容发到服务器吗？','不会。演示在浏览器本地匹配预设示例，不上传、不持久保存输入；请不要在演示中输入敏感资料。'],['它能保证回答正确吗？','不能。真实 AI 也可能产生错误。重要事实要核实来源，代码要运行测试，数据结论要重新计算。'],['如何获得更好的输出？','提供明确目标、受众、背景和格式，并说明限制条件。先生成草稿，再通过具体反馈迭代。'],['可以用于学习和教育吗？','可以作为讲解、练习和反馈的辅助工具。应鼓励独立思考，并遵循学校的作业与引用规则。'],['支持哪些语言？','本网站完整支持中文和英文。右上角切换后 URL 会更新，刷新保留当前语言。产品多语言能力是概念功能。'],['可以上传文件或连接知识库吗？','本页展示了资料辅助问答的概念界面，没有实际文件上传或第三方连接。正式实现需要额外的存储、检索与权限控制。'],['价格和优惠是真实的吗？','套餐是示例，月付和年付切换仅展示计费交互。不会收款，也不会创建订阅。'],['图表中的时间从哪里来？','来自明确标注的示例任务估算，并非真实测量。实际耗时与任务、资料质量及审核要求有关。'],['是否支持移动端与减少动画？','支持响应式布局、键盘操作和系统减少动画偏好。你也可以切换明暗主题。'],['可以将生成内容直接发布吗？','建议先审核事实、版权、隐私和品牌语气，再决定是否发布。最终判断由使用者负责。'],['如何查看这个页面的实现？','页面底部提供项目交付说明，仓库发布后会补充 GitHub 链接。README 记录运行方式、工具、设计取舍与验证结果。']
 ]:[['Is Luma AI a live AI service?','This is a concept-product landing page. Interfaces, plans and feedback demonstrate design and interactions. No live model or payment service is connected.'],['Does the demo send my input to a server?','No. It selects preset examples locally in your browser. Input is not uploaded or persisted. Please avoid entering sensitive material.'],['Are answers guaranteed to be correct?','No. Real AI can also make mistakes. Verify sources, test code and recalculate important figures.'],['How do I get better output?','Define your goal, audience, context, format and constraints. Start with a draft, then refine with specific feedback.'],['Can it help with education?','It can assist explanations, practice and feedback. Encourage independent thinking and follow your school’s assignment and citation rules.'],['Which languages are supported?','This website fully supports Chinese and English. Switching updates the URL, so refresh keeps the selected language. Product multilingual support is conceptual.'],['Can I upload files or connect a knowledge base?','The page illustrates reference-assisted answers but has no actual upload or integrations. Production use needs storage, retrieval and access control.'],['Are prices and discounts real?','Plans are illustrative. Monthly and annual billing switches demonstrate interaction only. No payment or subscription is created.'],['Where do the chart timings come from?','They are clearly labeled illustrative task estimates, not measurements. Actual time depends on the task, references and review requirements.'],['Does it support mobile and reduced motion?','Yes. Layouts adapt to small screens, controls support keyboards, and animations respect system preferences. Light and dark themes are available.'],['Can I publish generated content directly?','Review facts, rights, privacy and brand voice before publishing. The final decision remains with the user.'],['Where can I see the implementation?','Delivery notes are linked in the footer. A GitHub link will be added after publication. README records setup, tools, decisions and verification.']]).map(([title,description])=>({title,description})),
 };
}
export type Content = ReturnType<typeof getContent>;
